OP_DATA_GENERATION = "data_generation"
OP_TRAINING = "training"
OP_PREDICT = "predict"
OP_UPDATE_RESULT = "update_results"

OPERATION_LIST = [OP_DATA_GENERATION, OP_TRAINING, OP_PREDICT, OP_UPDATE_RESULT]
